---
title: Benton Yazzie Art
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: benton@bentonyazzie.com
description: 'Original art by Benton Yazzie.

'
baseurl: "/"
url: http://bentonyazzie.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
permalink: pretty
