---
title: Benton Yazzie Art
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: benton@bentonyazzie.com
description: 'Original art by Benton Yazzie.

'
baseurl: "/"
url: http://bentonyazzie.com
facebook_username: bentonyazzieart
amazon_url: Childrens-Books-Benton-Yazzie/s?rh=n%3A4%2Cp_27%3ABenton%20Yazzie
markdown: kramdown
permalink: pretty
